name = "story-craft-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "story-craft-app"
compatibility_date = "2024-01-01"

[env.production.vars]
NODE_ENV = "production"

# Database and JWT secrets should be set in Cloudflare Pages dashboard
# DATABASE_URL = "your-neon-postgres-connection-string"
# JWT_SECRET = "your-secure-jwt-secret"

[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[build]
command = "npm run build"
cwd = "."

[build.environment]
NODE_VERSION = "18"

# Pages configuration
[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
