name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for outdated packages
      run: npm outdated --json > outdated.json || true

    - name: Update minor and patch versions
      run: npm update

    - name: Run tests after updates
      run: npm test

    - name: Build to verify updates
      run: npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Weekly dependency updates'
        body: |
          Automated dependency updates:

          - Updated minor and patch versions
          - All tests passing ✅
          - Build successful ✅

          Please review the changes and merge if everything looks good.
        branch: dependency-updates
        delete-branch: true

  security-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Audit dependencies
      run: npm audit --audit-level high --json > audit.json || true

    - name: Fix security vulnerabilities
      run: npm audit fix

    - name: Run tests after security fixes
      run: npm test

    - name: Create Security PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: fix vulnerabilities'
        title: 'security: Fix security vulnerabilities'
        body: |
          🔒 Security vulnerability fixes:

          - Applied `npm audit fix` to resolve security issues
          - All tests passing ✅

          **Please review and merge promptly for security.**
        branch: security-updates
        delete-branch: true
        labels: |
          security
          dependencies
